brew "direnv"
brew "dockutil"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "iperf3"
brew "kubectx"
brew "kubernetes-cli"
brew "lftp"
brew "m-cli"
brew "mkcert"
brew "nss"
brew "nvm"
brew "shellcheck"
brew "starship"
brew "tree"

cask "betterzip"
cask "claude-code"
cask "codex"
cask "codexbar"
cask "comet"
cask "cursor"
cask "docker-desktop"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono"
cask "ghostty"
cask "google-chrome"
cask "google-drive"
cask "jetbrains-toolbox"
cask "lens"
cask "linearmouse"
cask "loopback"
cask "lulu"
cask "microsoft-edge"
cask "miniforge"
cask "nextcloud-vfs"
cask "onyx"
cask "postman"
cask "proxyman"
cask "raycast"
cask "rectangle-pro"
cask "slack"
cask "updf"
cask "visual-studio-code"
cask "zoom"

# Personal / entertainment apps. Comment out any that don't belong on an
# employer-owned Mac.
cask "discord"
cask "handbrake-app"
cask "iina"
cask "macpass"
cask "obs"
cask "opera"
cask "spotify"

# Other personal apps from the current machine, off by default. Uncomment only
# if suitable for the employer-owned Mac.
# cask "anydesk"
# cask "dropbox"
# cask "qbittorrent"
